train_file: ['uit/evjvqa_train.json']
valid_file: ['uit/evjvqa_train.json']
test_file : ['uit/official_evjvqa_public_test.json']

# answer_list: 'iglue/datasets/gqa/annotations/trainval_ans2label.json'
answer_list: ''
vqa_root: 'images/vqa-uit/train-images'
test_root: 'images/vqa-uit/public-test-images'
#test_file: {}
# zero-shot test set
# test_file: {
#   'bn': [ 'iglue/datasets/xGQA/annotations/few_shot/bn/test.json',
#           'iglue/datasets/gqa/annotations/trainval_ans2label.json' ],
#   'de': [ 'iglue/datasets/xGQA/annotations/few_shot/de/test.json',
#           'iglue/datasets/gqa/annotations/trainval_ans2label.json' ],
#   'en': [ 'iglue/datasets/xGQA/annotations/few_shot/en/test.json',
#           'iglue/datasets/gqa/annotations/trainval_ans2label.json' ],
#   'id': [ 'iglue/datasets/xGQA/annotations/few_shot/id/test.json',
#           'iglue/datasets/gqa/annotations/trainval_ans2label.json' ],
#   'ko': [ 'iglue/datasets/xGQA/annotations/few_shot/ko/test.json',
#           'iglue/datasets/gqa/annotations/trainval_ans2label.json' ],
#   'pt': [ 'iglue/datasets/xGQA/annotations/few_shot/pt/test.json',
#           'iglue/datasets/gqa/annotations/trainval_ans2label.json' ],
#   'ru': [ 'iglue/datasets/xGQA/annotations/few_shot/ru/test.json',
#           'iglue/datasets/gqa/annotations/trainval_ans2label.json' ],
#   'zh': [ 'iglue/datasets/xGQA/annotations/few_shot/zh/test.json',
#           'iglue/datasets/gqa/annotations/trainval_ans2label.json' ],
# }


## Vision Encoder
vision_config: 'configs/config_swinB_224.json'

use_clip_vit: False
# image_res: 384
# patch_size: 16

use_swin: True
image_res: 224
patch_size: 32


## Text Encoder (& Cross Encoder)
text_encoder: 'data/xlm-roberta-base'
text_num_hidden_layers: 6


## Training
num_dec_layers: 3
batch_size_train: 4
batch_size_test: 4
max_tokens: 40
k_test: 8


## Other Settings
optimizer: {opt: adamW, lr: 3e-5, weight_decay: 0.01, lr_mult: 2}
schedular: {sched: linear, lr: 3e-5, epochs: 30, num_warmup_steps: 0.1}
start_eval: 0  # epoch index


